#!/bin/bash

# GPLv2.
# (C) 2011 Mehdi Abaakouk

export REPREPRO_BASE_DIR=$HOME/archive/debian/

for dist in lenny squeeze sid; do
	for arch in amd64 i386 armel; do
		reprepro build-needing  $dist $arch | while read NAME VERSION DESC ; do
			echo "${NAME}_${VERSION} $dist $arch" 
		done
	done
done
